# Generated by Django 3.2.5 on 2021-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_temperature_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
