# Generated by Django 3.2.5 on 2021-07-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_temperature_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Broken', 'Broken')], default='Working', max_length=10, null=True),
        ),
    ]
