# Generated by Django 3.2.5 on 2021-07-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_temperature_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Ruthuparna', max_length=200),
            preserve_default=False,
        ),
    ]
